package game

type mcrFanMetadata struct {
	zh         string
	en         string
	points     int
	repeatable bool
	excludes   []FanID
}

var mcrFanMetadataByID = map[FanID]mcrFanMetadata{
	"mcr_01": {zh: "一般高", en: "Pure Double Chow", points: 1, repeatable: true},
	"mcr_02": {zh: "喜相逢", en: "Mixed Double Chow", points: 1, repeatable: true},
	"mcr_03": {zh: "连六", en: "Short Straight", points: 1, repeatable: true},
	"mcr_04": {zh: "老少副", en: "Two Terminal Chows", points: 1, repeatable: true},
	"mcr_05": {zh: "幺九刻", en: "Pung of Terminals or Honors", points: 1, repeatable: true},
	"mcr_06": {zh: "明杠", en: "Melded Kong", points: 1, repeatable: true},
	"mcr_07": {zh: "缺一门", en: "One Voided Suit", points: 1},
	"mcr_08": {zh: "无字", en: "No Honor Tiles", points: 1},
	"mcr_09": {zh: "自摸", en: "Self Drawn", points: 1},
	"mcr_10": {zh: "花牌", en: "Flower Tiles", points: 1, repeatable: true},
	"mcr_11": {zh: "边张", en: "Edge Wait", points: 1, excludes: []FanID{"mcr_12", "mcr_13"}},
	"mcr_12": {zh: "坎张", en: "Closed Wait", points: 1, excludes: []FanID{"mcr_11", "mcr_13"}},
	"mcr_13": {zh: "单钓将", en: "Pair Wait", points: 1, excludes: []FanID{"mcr_11", "mcr_12"}},
	"mcr_14": {zh: "箭刻", en: "Dragon Pung", points: 2, repeatable: true},
	"mcr_15": {zh: "圈风刻", en: "Prevalent Wind", points: 2},
	"mcr_16": {zh: "门风刻", en: "Seat Wind", points: 2},
	"mcr_17": {zh: "门前清", en: "Concealed Hand", points: 2},
	"mcr_18": {zh: "平和", en: "All Chows", points: 2, excludes: []FanID{"mcr_08"}},
	"mcr_19": {zh: "四归一", en: "Tile Hog", points: 2, repeatable: true},
	"mcr_20": {zh: "双同刻", en: "Double Pung", points: 2, repeatable: true},
	"mcr_21": {zh: "双暗刻", en: "Two Concealed Pungs", points: 2},
	"mcr_22": {zh: "暗杠", en: "Concealed Kong", points: 2, repeatable: true},
	"mcr_23": {zh: "断幺", en: "All Simples", points: 2, excludes: []FanID{"mcr_08"}},
	"mcr_24": {zh: "全带幺", en: "Outside Hand", points: 4},
	"mcr_25": {zh: "不求人", en: "Fully Concealed Hand", points: 4, excludes: []FanID{"mcr_09"}},
	"mcr_26": {zh: "双明杠", en: "Two Melded Kongs", points: 4, excludes: []FanID{"mcr_06"}},
	"mcr_27": {zh: "和绝张", en: "Last of its Kind", points: 4},
	"mcr_28": {zh: "碰碰和", en: "All Pungs", points: 6},
	"mcr_29": {zh: "混一色", en: "Half Flush", points: 6, excludes: []FanID{"mcr_07"}},
	"mcr_30": {zh: "三色三步高", en: "Mixed Shifted Chows", points: 6},
	"mcr_31": {zh: "五门齐", en: "All Types", points: 6},
	"mcr_32": {zh: "全求人", en: "Melded Hand", points: 6, excludes: []FanID{"mcr_13"}},
	"mcr_33": {zh: "双箭刻", en: "Two Dragon Pungs", points: 6, excludes: []FanID{"mcr_14"}},
	"mcr_34": {zh: "花龙", en: "Mixed Straight", points: 8},
	"mcr_35": {zh: "推不倒", en: "Reversible Tiles", points: 8, excludes: []FanID{"mcr_07"}},
	"mcr_36": {zh: "三色三同顺", en: "Mixed Triple Chow", points: 8, excludes: []FanID{"mcr_02"}},
	"mcr_37": {zh: "三色三节高", en: "Mixed Shifted Pungs", points: 8},
	"mcr_38": {zh: "双暗杠", en: "Two Concealed Kongs", points: 8, excludes: []FanID{"mcr_21", "mcr_22"}},
	"mcr_39": {zh: "妙手回春", en: "Last Tile Draw", points: 8, excludes: []FanID{"mcr_09"}},
	"mcr_40": {zh: "海底捞月", en: "Last Tile Claim", points: 8},
	"mcr_41": {zh: "杠上开花", en: "Out with Replacement Tile", points: 8, excludes: []FanID{"mcr_09"}},
	"mcr_42": {zh: "抢杠和", en: "Robbing the Kong", points: 8, excludes: []FanID{"mcr_27"}},
	"mcr_43": {zh: "无番和", en: "Chicken Hand", points: 8},
	"mcr_44": {zh: "全不靠", en: "Lesser Honors and Knitted Tiles", points: 12, excludes: []FanID{"mcr_17", "mcr_31"}},
	"mcr_45": {zh: "组合龙", en: "Knitted Straight", points: 12},
	"mcr_46": {zh: "大于五", en: "Upper Four", points: 12, excludes: []FanID{"mcr_08"}},
	"mcr_47": {zh: "小于五", en: "Lower Four", points: 12, excludes: []FanID{"mcr_08"}},
	"mcr_48": {zh: "三风刻", en: "Big Three Winds", points: 12, excludes: []FanID{"mcr_05"}},
	"mcr_49": {zh: "清龙", en: "Pure Straight", points: 16, excludes: []FanID{"mcr_03", "mcr_04"}},
	"mcr_50": {zh: "三色双龙会", en: "Three-Suited Terminal Chows", points: 16, excludes: []FanID{"mcr_02", "mcr_04", "mcr_08", "mcr_18"}},
	"mcr_51": {zh: "一色三步高", en: "Pure Shifted Chows", points: 16},
	"mcr_52": {zh: "全带五", en: "All Fives", points: 16, excludes: []FanID{"mcr_08", "mcr_23"}},
	"mcr_53": {zh: "三同刻", en: "Triple Pung", points: 16, excludes: []FanID{"mcr_20"}},
	"mcr_54": {zh: "三暗刻", en: "Three Concealed Pungs", points: 16, excludes: []FanID{"mcr_21"}},
	"mcr_55": {zh: "七对", en: "Seven Pairs", points: 24, excludes: []FanID{"mcr_13", "mcr_17"}},
	"mcr_56": {zh: "七星不靠", en: "Greater Honors and Knitted Tiles", points: 24, excludes: []FanID{"mcr_17", "mcr_31", "mcr_44"}},
	"mcr_57": {zh: "全双刻", en: "All Even Pungs", points: 24, excludes: []FanID{"mcr_08", "mcr_23", "mcr_28"}},
	"mcr_58": {zh: "清一色", en: "Full Flush", points: 24, excludes: []FanID{"mcr_07", "mcr_08", "mcr_29"}},
	"mcr_59": {zh: "一色三同顺", en: "Pure Triple Chow", points: 24, excludes: []FanID{"mcr_01"}},
	"mcr_60": {zh: "一色三节高", en: "Pure Shifted Pungs", points: 24},
	"mcr_61": {zh: "全大", en: "Upper Tiles", points: 24, excludes: []FanID{"mcr_08", "mcr_46"}},
	"mcr_62": {zh: "全中", en: "Middle Tiles", points: 24, excludes: []FanID{"mcr_08", "mcr_23"}},
	"mcr_63": {zh: "全小", en: "Lower Tiles", points: 24, excludes: []FanID{"mcr_08", "mcr_47"}},
	"mcr_64": {zh: "一色四步高", en: "Four Shifted Chows", points: 32, excludes: []FanID{"mcr_03", "mcr_51"}},
	"mcr_65": {zh: "三杠", en: "Three Kongs", points: 32, excludes: []FanID{"mcr_06", "mcr_22", "mcr_26", "mcr_38"}},
	"mcr_66": {zh: "混幺九", en: "All Terminals and Honors", points: 32, excludes: []FanID{"mcr_05", "mcr_24", "mcr_28"}},
	"mcr_67": {zh: "一色四同顺", en: "Quadruple Chow", points: 48, excludes: []FanID{"mcr_01", "mcr_19", "mcr_59"}},
	"mcr_68": {zh: "一色四节高", en: "Four Pure Shifted Pungs", points: 48, excludes: []FanID{"mcr_28", "mcr_60"}},
	"mcr_69": {zh: "清幺九", en: "All Terminals", points: 64, excludes: []FanID{"mcr_05", "mcr_08", "mcr_24", "mcr_28", "mcr_66"}},
	"mcr_70": {zh: "字一色", en: "All Honors", points: 64, excludes: []FanID{"mcr_05", "mcr_07", "mcr_24", "mcr_28", "mcr_66"}},
	"mcr_71": {zh: "小四喜", en: "Little Four Winds", points: 64, excludes: []FanID{"mcr_05", "mcr_48"}},
	"mcr_72": {zh: "小三元", en: "Little Three Dragons", points: 64, excludes: []FanID{"mcr_14", "mcr_33"}},
	"mcr_73": {zh: "四暗刻", en: "Four Concealed Pungs", points: 64, excludes: []FanID{"mcr_17", "mcr_21", "mcr_28", "mcr_54"}},
	"mcr_74": {zh: "一色双龙会", en: "Pure Terminal Chows", points: 64, excludes: []FanID{"mcr_01", "mcr_04", "mcr_07", "mcr_18", "mcr_29", "mcr_58"}},
	"mcr_75": {zh: "大四喜", en: "Big Four Winds", points: 88, excludes: []FanID{"mcr_05", "mcr_15", "mcr_16", "mcr_28", "mcr_48"}},
	"mcr_76": {zh: "大三元", en: "Big Three Dragons", points: 88, excludes: []FanID{"mcr_14", "mcr_33"}},
	"mcr_77": {zh: "绿一色", en: "All Green", points: 88},
	"mcr_78": {zh: "九莲宝灯", en: "Nine Gates", points: 88, excludes: []FanID{"mcr_05", "mcr_07", "mcr_08", "mcr_17", "mcr_29", "mcr_58"}},
	"mcr_79": {zh: "四杠", en: "Four Kongs", points: 88, excludes: []FanID{"mcr_06", "mcr_13", "mcr_22", "mcr_26", "mcr_28", "mcr_38", "mcr_65"}},
	"mcr_80": {zh: "连七对", en: "Seven Shifted Pairs", points: 88, excludes: []FanID{"mcr_07", "mcr_08", "mcr_13", "mcr_17", "mcr_29", "mcr_55", "mcr_58"}},
	"mcr_81": {zh: "十三幺", en: "Thirteen Orphans", points: 88, excludes: []FanID{"mcr_17", "mcr_24", "mcr_31", "mcr_66"}},
}
